### ISSUE TITLE
Unable to run npm install: version not found: tns-core-modules@1.3.0

### ISSUE THREAD

**Issue by HriBB** [NativeScript/sample-Tasks#27]
System Version: OS X 10.10.5 (14F27)
Kernel Version: Darwin 14.5.0

```
usse1:nativescript bojan$ git clone git@github.com:NativeScript/sample-Tasks.git
Cloning into 'sample-Tasks'...
remote: Counting objects: 3750, done.
remote: Total 3750 (delta 0), reused 0 (delta 0), pack-reused 3750
Receiving objects: 100% (3750/3750), 8.19 MiB | 3.83 MiB/s, done.
Resolving deltas: 100% (1804/1804), done.
Checking connectivity... done.

usse1:nativescript bojan$ cd sample-Tasks/

usse1:sample-Tasks bojan$ tns doctor
No issues were detected.

usse1:sample-Tasks bojan$ ./run.sh 
npm WARN package.json sample-Tasks@1.0.0 license should be a valid SPDX license expression
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! version not found: tns-core-modules@1.3.0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bojan/www/nativescript/sample-Tasks/npm-debug.log
usse1:sample-Tasks bojan$ 
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose readDependencies loading dependencies from /Users/bojan/www/nativescript/sample-Tasks/package.json
6 warn package.json sample-Tasks@1.0.0 license should be a valid SPDX license expression
7 verbose install where, deps [ '/Users/bojan/www/nativescript/sample-Tasks',
7 verbose install   [ 'tns-core-modules', 'typescript' ] ]
8 verbose install where, peers [ '/Users/bojan/www/nativescript/sample-Tasks', [] ]
9 verbose installManyTop reading for lifecycle /Users/bojan/www/nativescript/sample-Tasks/package.json
10 info preinstall sample-Tasks@1.0.0
11 verbose readDependencies loading dependencies from /Users/bojan/www/nativescript/sample-Tasks/package.json
12 silly cache add args [ 'typescript@1.5.3', null ]
13 verbose cache add spec typescript@1.5.3
14 silly cache add parsed spec { raw: 'typescript@1.5.3',
14 silly cache add   scope: null,
14 silly cache add   name: 'typescript',
14 silly cache add   rawSpec: '1.5.3',
14 silly cache add   spec: '1.5.3',
14 silly cache add   type: 'version' }
15 silly addNamed typescript@1.5.3
16 verbose addNamed "1.5.3" is a plain semver version for typescript
17 silly mapToRegistry name typescript
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/typescript
21 verbose addNameVersion registry:https://registry.npmjs.org/typescript not in flight; fetching
22 silly cache add args [ 'tns-core-modules@1.3.0', null ]
23 verbose cache add spec tns-core-modules@1.3.0
24 silly cache add parsed spec { raw: 'tns-core-modules@1.3.0',
24 silly cache add   scope: null,
24 silly cache add   name: 'tns-core-modules',
24 silly cache add   rawSpec: '1.3.0',
24 silly cache add   spec: '1.3.0',
24 silly cache add   type: 'version' }
25 silly addNamed tns-core-modules@1.3.0
26 verbose addNamed "1.3.0" is a plain semver version for tns-core-modules
27 silly mapToRegistry name tns-core-modules
28 silly mapToRegistry using default registry
29 silly mapToRegistry registry https://registry.npmjs.org/
30 silly mapToRegistry uri https://registry.npmjs.org/tns-core-modules
31 verbose addNameVersion registry:https://registry.npmjs.org/tns-core-modules not in flight; fetching
32 verbose request uri https://registry.npmjs.org/tns-core-modules
33 verbose request no auth needed
34 info attempt registry request try #1 at 09:59:45
35 verbose request id 482ef7de3d8e8030
36 verbose etag "EKCKT07YBCK65I3TONPH01O7L"
37 http request GET https://registry.npmjs.org/tns-core-modules
38 verbose request uri https://registry.npmjs.org/typescript
39 verbose request no auth needed
40 info attempt registry request try #1 at 09:59:45
41 verbose etag "9KCJCABYN3NWEDIDRNU9TTFE0"
42 http request GET https://registry.npmjs.org/typescript
43 http 304 https://registry.npmjs.org/tns-core-modules
44 silly get cb [ 304,
44 silly get   { date: 'Mon, 14 Sep 2015 07:59:45 GMT',
44 silly get     via: '1.1 varnish',
44 silly get     'cache-control': 'max-age=60',
44 silly get     etag: '"EKCKT07YBCK65I3TONPH01O7L"',
44 silly get     age: '57',
44 silly get     connection: 'keep-alive',
44 silly get     'x-served-by': 'cache-fra1225-FRA',
44 silly get     'x-cache': 'HIT',
44 silly get     'x-cache-hits': '1',
44 silly get     'x-timer': 'S1442217585.886157,VS0,VE0',
44 silly get     vary: 'Accept' } ]
45 verbose etag https://registry.npmjs.org/tns-core-modules from cache
46 verbose get saving tns-core-modules to /Users/bojan/.npm/registry.npmjs.org/tns-core-modules/.cache.json
47 http 304 https://registry.npmjs.org/typescript
48 silly get cb [ 304,
48 silly get   { date: 'Mon, 14 Sep 2015 07:59:45 GMT',
48 silly get     via: '1.1 varnish',
48 silly get     'cache-control': 'max-age=60',
48 silly get     etag: '"9KCJCABYN3NWEDIDRNU9TTFE0"',
48 silly get     age: '0',
48 silly get     connection: 'keep-alive',
48 silly get     'x-served-by': 'cache-fra1220-FRA',
48 silly get     'x-cache': 'HIT',
48 silly get     'x-cache-hits': '1',
48 silly get     'x-timer': 'S1442217585.870053,VS0,VE715',
48 silly get     vary: 'Accept' } ]
49 verbose etag https://registry.npmjs.org/typescript from cache
50 verbose get saving typescript to /Users/bojan/.npm/registry.npmjs.org/typescript/.cache.json
51 silly cache afterAdd typescript@1.5.3
52 verbose afterAdd /Users/bojan/.npm/typescript/1.5.3/package/package.json not in flight; writing
53 verbose afterAdd /Users/bojan/.npm/typescript/1.5.3/package/package.json written
54 verbose stack Error: version not found: tns-core-modules@1.3.0
54 verbose stack     at setData (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:137:12)
54 verbose stack     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
54 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
54 verbose stack     at fixName (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:29:5)
54 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
54 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
55 verbose statusCode 404
56 verbose cwd /Users/bojan/www/nativescript/sample-Tasks
57 error Darwin 14.5.0
58 error argv "node" "/usr/local/bin/npm" "install"
59 error node v0.12.7
60 error npm  v2.12.1
61 error version not found: tns-core-modules@1.3.0
62 error If you need help, you may report this error at:
62 error     <https://github.com/npm/npm/issues>
63 verbose exit [ 1, true ]
```

**Comment by hamorphis** [comment]
Version 1.3.0 is not released yet. I am currently adapting the app for it. In a couple of days it would be working.
